Team5_Workshop5/Team5_Workshop5/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Team5_Workshop5.Models;

namespace Team5_Workshop5.Controllers
{
    public class ProductDetailsController : Controller
    {
        // GET: ProductDetails
        public ActionResult Index()
        {
            if (Session["UserID"] != null)
            {
                int custId = Convert.ToInt32(Session["CustomerID"]); // Needs to be passed in from session
                List<ProductDetails> pdList = new List<ProductDetails>();
                pdList = ProductDetailsDB.GetProductDetails(custId);
                decimal total = 0;
                foreach (ProductDetails p in pdList)
                {
                    total += p.Price;
                }
                ViewBag.total = total;
                return View(pdList);
            }
            else
            {
                return RedirectToAction("LoginCustomer", "Customer");
            }
        }

        //// GET: ProductDetails/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}
    }
}

Team5_Workshop5/Team5_Workshop5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
 @** Name: Bilal Ahmad
 * Date: Feb 13, 2020
 * Purpose: Layout page for the all the views
     *@


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Travel Experts</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
            <div class="container">
                @if (Session["UserID"] != null)
                {
                    @Html.ActionLink("Dashboard", "Index", "ProductDetails", null, new { @class = "navbar-brand DashboardCustom" })

                }
                else
                {
                    @Html.ActionLink("Travel Experts", "LoginCustomer", "Customer", null, new { @class = "navbar-brand" })
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapseNav" aria-controls="collapseNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="collapseNav">
                    <ul class="navbar-nav mr-auto">
                        @*<li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link active" })</li>*@
                        @*<li class="nav-item">@Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })</li>*@
                        @*<li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })</li>*@

                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        @if (Session["UserID"] != null)
                        {
                            @Html.ActionLink(Session["CustFirstName"].ToString(), "PersonalInformation", "Customer", null, new { @class = "nav-link" })

                            @*@Html.ActionLink("Personal Info", "PersonalInformation", "Customer", new { UserID = Session["UserID"] }, new { @class = "nav-link" })*@
                            @Html.ActionLink("Logout", "Logout", "Customer", null, new { @class = "nav-link" })
                        }
                        else
                        {
                            @Html.ActionLink("Login", "LoginCustomer", "Customer", null, new { @class = "nav-link" })
                            @Html.ActionLink("Register", "CustomerRegistration", "Customer", null, new { @class = "nav-link" })

                        }
                        @*<input class="form-control mr-sm-2" type="text" placeholder="Search">*@
                        @*<button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>*@
                    </form>
                </div>
            </div>
        </nav>
    </div>
    <div class="container body-content mt-5">
        @RenderBody()
        <hr />
        
    </div>
    <footer class="row justify-content-center bottom pt-4">
        <p>&copy; @DateTime.Now.Year - Travel Experts</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>